### ISSUE TITLE
install.php可以被利用来恶意重装靶场

### ISSUE THREAD

**Issue by xiezhuojin** [zhuifengshaonianhanlu/pikachu#2]
不知道这算不算漏洞。。。刚入门。index.php中通过检验数据库是否可以连上数据库来判断是否配置完成。但是却可以直接访问install.php来直接覆盖掉原来数据库中的数据。我觉得应该在配置文件中设置一个$installed变量来控制已经安装，然后install.php读取这个变量来判断是否需要安装。

**Comment by zhuifengshaonianhanlu** [comment]
你小子挺厉害啊，靶场里面找漏洞。
你就当是靶场里面的一个“用来练习的漏洞”吧。（不过实际环境中，这种情况确实是有问题的）

**Comment by xiezhuojin** [comment]
其实我是试着练审计的，里面一些知识我还不熟，比如sql注入一点不熟悉。还有一个问题是今天看出来的，sqli_iu/sqli_mem.php里面把用户信息拿出来时可以进行xss攻击，注册时只对sql进行escape，输出时没有escape
